export enum DatabaseCategories {
    DAILY_SPECIALS = "Daily",
    APPETIZERS = "Appetizers",
    CHICKEN = "Chicken",
    PORK_BEEF = "PorkBeef",
    SALADS = "Salads",
    SANDWICHES = "Sandwiches",
    SEAFOOD = "Seafood",
    SIDES = "Sides",
    SOUPS = "Soups",
    KIDS = "Kids",
    COFFEE_TEA = "CoffeeTea",
    DRINKS = "Drinks",
    JUICES = "Juices",
    DESSERTS = "Desserts",
    MILKSHAKES = "Milkshakes",
}

export const CategoryNames = {
    [DatabaseCategories.APPETIZERS]: "Appetizers / Aperitivos",
    [DatabaseCategories.CHICKEN]: "Chicken / Pollo",
    [DatabaseCategories.COFFEE_TEA]: "Coffee and Tea / Café y Té",
    [DatabaseCategories.DAILY_SPECIALS]: "Daily Specials / Especialidades de la Semana",
    [DatabaseCategories.DESSERTS]: "Desserts / Postres",
    [DatabaseCategories.DRINKS]: "Drinks / Bebidas",
    [DatabaseCategories.JUICES]: "Juices / Jugos",
    [DatabaseCategories.KIDS]: "Kids Menu / Menu para Niños",
    [DatabaseCategories.MILKSHAKES]: "Milkshakes / Batidos",
    [DatabaseCategories.PORK_BEEF]: "Pork & Beef / Cerdo y Res",
    [DatabaseCategories.SALADS]: "Salads / Ensaladas",
    [DatabaseCategories.SANDWICHES]: "Sandwiches",
    [DatabaseCategories.SEAFOOD]: "Seafood / Mariscos",
    [DatabaseCategories.SIDES]: "Side Orders / Acompañantes",
    [DatabaseCategories.SOUPS]: "Soups / Sopas"
}